- sections/communication/ipc.html
Good for professional appearance
> Fix typographical error in ipc.html: 'recieve' -> 'receive'

- package.json
Came out today http://electron.atom.io/devtron
> Add devtron as dependency

- assets/css/variables.css
color-bg is defined twice in assets/css/variables.css.
> Removing duplicate of color-bg variable in variable.css

- sections/about.html
There's a small typo in the intro, a space between "un" and "changing".
> Change 'un changing' to 'unchanging'

- renderer-process/communication/invisible-msg.js
> remove unused var

- renderer-process/communication/invisible-msg.js
- sections/communication/ipc.html
> Fix bug for commnicate with invisible window demo

- sections/communication/ipc.html
- sections/media/desktop-capturer.html
- sections/media/pdf.html
- sections/menus/menus.html
- sections/menus/shortcuts.html
- sections/native-ui/dialogs.html
- sections/native-ui/ex-links-file-manager.html
- sections/native-ui/tray.html
- sections/system/app-sys-information.html
- sections/system/clipboard.html
- sections/system/protocol-handler.html
- sections/windows/crash-hang.html
- sections/windows/windows.html
> Update doc links for new site

- auto-updater.js
as in https://github.com/develar/onshape-desktop-shell/blob/master/src/WinSquirrelStartupEventHandler.ts
> updated updateExe path

- package.json
- script/windows-store.js
Generates a `.appx` to be eventually uploaded to the Windows store.
> Add Windows Store build script

- sections/media/desktop-capturer.html
- sections/media/pdf.html
Was trying to copy these paths to use them in the terminal and noticed they weren't selectable.
/cc @jlord
> Make pdf/screenshot paths selectable

- package.json
- tests/index.js
This bit me and @jlord a few times while working on the Google accessibility auditing tools.
> update electron prebuilt for testing new devtron features

- CONTRIBUTING.md
This PR adds a section to `CONTRIBUTING.md` on releasing this app. The core team handles this but documenting it helps everyone 🌈 ✨ 
🍐 @zeke 
📞 @kevinsawicki 👀
> Add section on release steps

- README.md
This adds a link in the `README` to a translated version of the app created by @fuchao2012 🎉 (thanks!).
I also added a note just to let people know that the two versions may update independently. 
Closes #259
> Add link to translated version 

- .gitattributes
- CONTRIBUTING.md
- renderer-process/windows/manage-window.js
- renderer-process/windows/using-window-events.js
See discussion in https://github.com/electron/electron-api-demos/pull/79 for more context. 
We don't use arrow functions in demos.
> Remove arrow functions

- sections/communication/invisible.html
- sections/communication/ipc.html
- sections/media/desktop-capturer.html
- sections/media/pdf.html
- sections/menus/menus.html
- sections/menus/shortcuts.html
- sections/native-ui/dialogs.html
- sections/native-ui/ex-links-file-manager.html
- sections/native-ui/tray.html
- sections/system/app-sys-information.html
- sections/system/clipboard.html
- sections/system/protocol-handler.html
- sections/windows/crash-hang.html
- sections/windows/windows.html
Fix the wrong html tags
Fixed duplicate id tags
> Fix the .html file tags in sections directory

- sections/system/app-sys-information.html
Fix typo in System - Get app or user system information - Get version information
> Fix typo in System section

- license.md
> update license year to 2018

- main-process/system/protocol-handler.js
Fixes protocol handling of unpackaged apps on Windows.
/cc @MarshallOfSound
> fix: unpkgd protocol handling on windows

- main-process/system/protocol-handler.js
> fix: require path when using it

- package-lock.json
- package.json
Seems that all features in this demo are backward compatible in Electron v5
https://github.com/electron/electron/releases/tag/v5.0.0
> build: upgrade to electron v5

- package-lock.json
- package.json
> fix: update packages for recent vulnerabilities

- assets/css/nativize.css
> fix: make code element selectable
