README.md
looks like this repo was moved from the atom org to electron 😄
=> Update repository URL references in README

sections/menus/shortcuts.html
The page wasn't found anymore and the redirect didn't work.
=> fix broken link to global shortcut api

main-process/menus/shortcuts.js, sections/menus/shortcuts.html
`Cmd-Alt-D` already does something on Mac so use `Cmd-Alt-K` instead (K for keyboard shortcut).
/cc @jlord 
Closes #179
=> Use different shortcut keybinding

main-process/native-ui/tray/tray.js
If a user hits the red traffic light on OS X to close the app window we keep the app running (this is default behavior) so it can be re-activated by clicking the dock icon. But! Should the user have the tray icon on at the time they close this leaves the tray icon there with no renderer process (and causes an error if you then try and remove the icon, see #189).
In the other OSes we quit the app and the tray icon is removed at that time. 
This PR adds a listener to the `all-windows-closed` event and removes the tray icon. Technically we only need to do this on OS X but I kept it simple and didn't check the platform (and packaged and tried it on Linux, I don't think it interferes with it's default behavior). 
cc @kevinsawicki 
Closes #189
=> Remove tray icon when all windows are closed

assets/mac/child.plist, assets/mac/info.plist, assets/mac/parent.plist, auto-updater.js, main.js, package.json, script/mas.sh
Adds `npm run mas` to generate a build for the Mac App Store.
/cc @jlord 🍐
=> Mac App Store build

main-process/native-ui/tray/tray.js
`window-all-closed` could emit on the app before the `appIcon` was created which would give you a `cannot call method destroy on undefined` error dialog.
/cc @jlord 
Refs https://github.com/electron/electron-api-demos/pull/210
=> Guard against no app icon

renderer-process/system/screen-information.js, sections/system/app-sys-information.html
This pull request changes the demo to use the `.size` method which provides the raw dimensions of the primary display. 
It then adds a ProTip section to let users know that they can use `.workArea` and `.workAreaSize` to get the dimensions of the space actually available to their app.
Closes #221
=> Update screen information demo

index.html, main-process/menus/application-menu.js, main.js, script/mas.sh, tests/index.js
The name `Electron API Demos` was rejected since you can't have `demo`/`demos`/`demonstration` in the name.
This renames it for only the app store build to `Electron APIs`.
Will merge if/when it gets approved.
=> Rename app to get approved in Mac App Store

renderer-process/windows/create-window.js, renderer-process/windows/frameless-window.js, renderer-process/windows/manage-window.js, renderer-process/windows/process-crash.js, renderer-process/windows/process-hang.js
Currently the app shows an exception dialog in the following scenario:
- Start the app
- Click Create and manage windows from the left nav
- Expand Create a new window
- Click View Demo
- Quit the app
I think this is happening because the `closed` event is being listened for over RPC and so the window is already released by the time the event fires.
This pull request switches to using the `close` event which fires before `closed` and seems to prevent this error while still `null`-ing out the `win` variable.
http://electron.atom.io/docs/api/browser-window/#event-close
/cc @jlord
=> Use close event instead of closed

assets/mac/parent.plist
Adding this [entitlement](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1) gets the open and save dialog demos working in the mac app store build.
/cc @jlord 👀 
Refs #227
=> Enable user-selected entitlement for open/save demo

main-process/media/pdf.js, renderer-process/media/desktop-capturer.js
This appears to fix the pdf and screenshot demos in the mac app store build and still opens the Preview app on Mac and photos/IE on Windows so it seems to behave the same.
This is an alternative to #230 
Refs #227
=> Use shell.openExternal instead of shell.openItem

main-process/native-ui/tray/tray.js, renderer-process/native-ui/tray/tray.js
Don't call `appIcon.destroy()` in the click event, because it causes a crash in OS X 10.10.x. Instead, use `ipc` and the `remove-tray` channel. 
Closes #220
=> Don't appIcon.destroy() in click event

assets/css/global.css
This updates the font stack.
`'.SFNSText-Regular'` is a private font name and looks like it [will be removed/changed](https://github.com/atom/atom/pull/12002#issue-161019262) in macOS Sierra. `'BlinkMacSystemFont'` should be more future proof.
=> Update font stack

index.html, package.json, sections/about.html, sections/system/clipboard.html, tests/index.js
This pull request adds a spec that audits each section for accessibility errors returned from Spectron's `auditAccessibility()` helper.
The contrast rule is disabled due to the app using background gradients which are not currently supported by the accessibility library, https://github.com/GoogleChrome/accessibility-developer-tools/issues/79
The changes to the `.html` files were to get the specs passing, there were a few current issues with missing labels and alt text.
/cc @jlord @zeke
=> Add spec that audits accessibility

package.json
Love the demo. Was playing around with it and it took me an extra minute or two to figure out what linting errors I was tripping after adjusting some files. Adding [`snazzy`](https://www.npmjs.com/package/snazzy) helped me see what the errors are:
Feel free to just close if adding `snazzy` is not desired.
=> Add snazzy to linting

script/mas.sh
Spotted this while browsing the repository. Simple change to:
Fix spelling: work => word
=> Update mas.sh spelling & grammar

script/release.js
Fixes #267 
This runs `heroku whoami` before building the release and fails with a helpful message if the user is not logged in (or is logged in with a non-github.com email address.)
@kevinsawicki @Haacked
=> check Heroku login status before release

tests/index.js
Tests were failing on windows. 
The app did not seem to start, looks like this issue: http://stackoverflow.com/questions/37343150/spectron-and-electron-without-exe-files
Eventually, the timeout will fire without even the `before` to be finished. 
This PR fixes that. 
I've also addressed the `userDataPath` since it was only configured for OSX. 
Tests are still failing on Windows btw, but that seems unrelated. This line evaluates to `false` when I run the tests.
.browserWindow.isFocused().should.eventually.be.true
https://github.com/electron/electron-api-demos/blob/master/tests/index.js#L113
=> Fixes for tests for Windows

package.json
Working toward #294 
I just did a fresh `rm -rf node_modules && npm i && npm t`. The app window appears on screen, but the test suite is hanging on setup and it times out before any of the tests are run.
The [docs for `app.start()`](https://github.com/electron/spectron/#start) say that it returns a promise when the app is ready, but it seems the `setupApp` function is never reached.
Any ideas, @kevinsawicki?
=> Keep electron and spectron minor version numbers in sync

assets/demo-btns.js, assets/nav.js, package.json, test/index.js
Note: In **`nav.js`** I had to move the logic to set the saved section as the active section from the top of the file to the bottom, because the `click` handlers had to be bound first. Previously, electron-json-config returned a callback inside of which `click()` was called. It was a race condition and came to light when implementing electron-settings because the logic here is synchronous.
I also delete the active demo setting if the user collapses the demo, in **`demo-btns.js`**.
Fixes #251
=> Replace `electron-json-storage` with `electron-settings`

package.json
Previous versions had `electron` as a dependency, whereas it should be a dev dependency. This was causing issues with code signing the application with an Apple Developer ID Application certificate.
See [electron-settings#68](https://github.com/nathanbuchar/electron-settings/issues/68).
=> Update electron-settings to version 3.0.7

renderer-process/windows/using-window-events.js
This is just a minor fix to avoid multiple subscriptions to a click handler. In this particular case it is not essential as win.focus() would be idempotent, but considering click handler may be something more complex the pattern itself may be misleading.
=> Fix multiple handlers subscriptions

sections/native-ui/dialogs.html
Fixed typo from "interupting" to "interrupting".
=> Fix typo (from interupting to interrupting).

sections/menus/menus.html
Updates from dead link to working link
=> update MacOS keyboard shortcut link

test/index.js, test/setup.js
Moved setup functions including 
```
removeStoredPreferences,
getUserDataPath,
setupApp
```
into another file so that they can be reused. Unsure if i should also move `startApp` and `restartApp` into `setup.js` for reusability?
=> Split tests into setup.js and index.js

sections/menus/menus.html
I checked out the demo and the menu link was to the apple page for keyboards. Didn't really make sense to me.
=> replaces keyboard link with menu link

package.json
now that we have a stable 1.8.x version in npm, bump our dependency from to 1.8.x
=> bump electron devDependencies to 1.8.2

renderer-process/media/desktop-capturer.js
It was crashing on undefined 'NativeImage.toPng()', was deprecated (new version is NativeImage.toPNG()) in 1.7 and removed in 2.0.
=> Fix screenshot demo

renderer-process/windows/using-window-events.js
Fixes https://github.com/electron/electron-api-demos/issues/350.
Move `hideFocusBtn` up above `win.on('focus', hideFocusBtn)`so that it does not error and say the variable is not declared.
=> Fix empty Blur and Focus demo

package.json
Resolves https://github.com/electron/electron-api-demos/issues/357.
Update to Electron `v2.0.0` now that it's gone stable.
/cc @zeke @ckerr
=> Update to v2.0.0

package-lock.json, package.json
This PR fixes dependency security vulns identified with `npm audit`.
Includes some breaking changes, so this may need additional testing before it's ready for prime time.
/cc @zeke
=> Fix majority of dependency vulns

.travis.yml
Update `.travis.yml` to use latest Node.js and an LTS release for
testing. Currently, Node.js 4.x is hard-coded. Node.js 4.x is currently
unsupported by the Node.js project. There will be no more 4.x releases.
Any security vulnerabilities or other bugs currently in 4.x will be there
forever.
=> use current and LTS Node.js in CI

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This PR updates the README and other contribution documentation to reflect our new primary website and Code of Conduct email.
=> fix: update links for new emails and website

package.json
Refs: https://github.com/electron/electron-api-demos/issues/385
Fixes issue whereby we saw
```
$ npx electron-api-demos
Cannot find module 'electron'
```
by moving the `electron` dependency to from `devDeps` to `deps`.
/cc @zeke
=> fix: move electron to dependencies

package.json, script/release.js
Fix asset name zipping in `release.js`, remove unnecessary heroku-related code, and bump version # to `1.5.1`
/cc @zeke
=> Bump version 1.5.1

main.js
Potential fix for errors in `npx` and `npm` installation as a result of failed checks in `update-electron-app`.
/cc @zeke
=> fix: don't require update-electron-app if cli

main.js
What it says on the tin.
Update deprecated `app.makeSingleInstance` to `app.requestSingleInstanceLock()` and `app.on('second-instance', cb)`
=> fix: update deprecated makeSingleInstance

main.js
The PR removes unnecessary bits
=> chore: clear code after start of requestSingleInstanceLock

package-lock.json, package.json, script/release.js
This PR updates the release script:
* Use `async`/`await` everywhere
* Use `@octokit/rest` instead of manual requests
* "Gracefully" handle GitHub asset upload failures
Until this is fixed on GitHub's end, the best we can do is prompt the releaser to manually delete the incomplete asset from the draft release and try again
=> chore: update release script

main.js
Follow-up to https://github.com/electron/electron-api-demos/pull/392.
Verdict: [`update-electron-app`](https://github.com/electron/update-electron-app/blob/master/index.js#L25) was using [`electron-is-dev`](https://github.com/sindresorhus/electron-is-dev/blob/master/index.js#L9) to determine whether or not the app was in dev mode and therefore whether or not to try and update – however! It was using `app.isPackaged` as a fallback! 
That API was not introduced until v3.0.0, and `electron-api-demos` itself wasn’t using `^3.0.0` until late October, so i believe it was returning an incorrect value as a result :rocket:
/cc @zeke @ckerr
=> chore: no longer explicitly wrap update-electron-app in check

main.js
Needed for the current code structure, but disabled by default in 5.0.
CC @codebytere
=> fix: enable node integration

renderer-process/communication/invisible-msg.js
Same as #429, but for invisible window demo
=> fix: enable node integration to make invisible window demo work

renderer-process/windows/process-crash.js, renderer-process/windows/process-hang.js
Hi! 👋
I've noticed, that crash and hang demos do not work and there's `process is not defined` errors in demo windows.
This PR fixes that by enabling node integration, so demo windows have access to `process`.
=> fix: crash and hang demos

renderer-process/media/desktop-capturer.js
The desktop-capturer demo not working in my mac. After debugging, I think there is a case error in the code.
=> fix: case error in desktop-capturer demo

renderer-process/media/desktop-capturer.js, renderer-process/system/screen-information.js
renderer process accesses main process using remote module
=> fix: Cannot read property 'getPrimaryDisplay' of undefined

README.md
Hello everyone!
I Add a link translated into [Japanese Version](https://github.com/LeeDDHH/electron-api-demos-ja) in the README.
wants fellows to check :)
=> docs: Add link to translated japanese
